### ISSUE TITLE
Initial Investigation for Natural Language Tools

### ISSUE THREAD

**Issue by BeniGal** [BeniGal/virtual-assistent-fakanal-ubbse2016#2]
The scope of the issue is to investigate and / or find already existing natural language tools.

A decision should be made if we need to implement our own tool or we can use third-party tools for analyzing language.
The issue is completed when the decision has been made.

**Comment by code31415926535** [comment]
Some usefull links:
http://aylien.com/text-api
http://blog.mashape.com/list-of-25-natural-language-processing-apis/
www.textrazor.com/demo

**Comment by code31415926535** [comment]
We decided to use pythons natural language toolkit.
