### ISSUE TITLE
Create Inital Plan of the Backend

### ISSUE THREAD

**Issue by code31415926535** [BeniGal/virtual-assistent-fakanal-ubbse2016#5]
The scope of this issue is to define the core structure of the back-end.

The outcome of the issue should be a diagram describing the general structure of the back-end.

This structure should contain the core components that should remain consistent.

**Comment by BeniGal** [comment]
LucidChart may be used for the diagram.

**Comment by code31415926535** [comment]
Here are some usefull links to consider:
https://www.tutorialspoint.com/nodejs/nodejs_restful_api.htm
https://www.npmjs.com/package/mongoose-rbac
